requests :
  delay : 60
  start : 1644848100.0
  end : 1744848400.0
output :
  nodes : "nodes.json"
  links : "links.json"
scan :
  game_id : "509660"
  language : ""
  top_lenght : 10
  streamers : false
creds :
  id_twitch : "t9d0w8edfe5g5j49k5x16nivbgf23o"
  secret_twitch : "hmkn87qu8aqxoro716f5v7x7mtc49l"