chat_scan:
  enable: true
  words_lookup:
    - zlan
    - ingdoc
    - gdoc
    - ingés du gdoc
    - ingédoc
    - ingdocs
  words_count :
    - zrtalien
    - zrtw
    - lul
    - kappa
    - zrtl
    - kekw
    - alienjam
    - catjam
    - guillgg
    - guillzlan
    - poncefleur
    - poncecoeur
    - poncejam
cmd_config: false
creds:
  id_twitch: 
  secret_twitch: 
output:
  links: links.json
  nodes: nodes.json
requests:
  delay: 60
  end: 1649279800.0
  start: 1649278800.0
scan:
  game_id: false
  global_scan: false
  language: false
  streamers:
  - zerator
  - mickalow
  - slideforever
  - gotaga
  - leaprima
  - woody
  - titavion
  - sratuke
  - tomtom
  - galino
  - etoiles
  - befreesh
  - kameto
  - arkantors
  - malganyr
  - mitsu
  - nawk_
  - nozadah
  - kocomen
  - ciremyxx
  - etitrane
  - aikko
  - koka
  - funka
  - og_tkl
  - madmoizelle
  - missclictv
  - shakaam
  - nems
  - signys
  - mpe__
  - cascacita
  - femimarss
  - lemed
  - ponce
  - onutrem
  - wingobear
  - aloonea
  - evalunna
  - einifox
  - bauerpartenlive
  - hugolisoir
  - zetetone
  - kiroko
  - pegafil
  - batou
  - moman
  - berlu
  - rivenzi
  - willokhlass
  - kylex
  - marcote
  - hidan_ow
  - jimdz
  - romainjacques_
  - poppielala
  - choopchoop
  - littlebigwhale
  - cokoooooo
  - gomart
  - bichard
  - dragow
  - fatou
  - gamingo
  - neptune
  - krimstation
  - softstyl
  - malm
  - aytheak
  - theguill84
  - martinponk
  - jimmyboy
  - rasmelthor
  - maylie_tv
  - zuka
  - ravare
  - liivoo
  - aspigtv
  - celezis
  - anh_
  - kennystream
  - hqrdest
  - nuja
  - lolypokicake
  - lyden
  - scurb
  - pastequehachee
  - takamari
  - jussetain
  - nykho
  - titatitutu
  - taaktm
  - keolys
  - frezzfire
  - helliodar
  - gaspow
  - d7rl
  - kioss3000
  - maevys
  - lebiggy
  - niamor
  - nateos
  - jlfakemonster
  - jlsaitaike
  - leaf__ow
  - shuh1_ow
  - oslo
  - weesie
  - lunium
  - flashshadow
  - el8kun
  - poneeeyclub
  - arthurray
  top_length: false
